package me.jayer.hdata.mongodb

import org.apache.beam.sdk.coders.SerializableCoder
import org.apache.beam.sdk.schemas.Schema
import org.apache.beam.sdk.transforms.Combine
import org.apache.beam.sdk.transforms.DoFn
import org.apache.beam.sdk.values.Row
import org.bson.BsonDocument
import org.bson.Document
import org.bson.types.Decimal128
import java.io.Serializable

/**
 * MongoDB push-down aggregation: translates `count` / `sum` / `min` / `max` / `avg` into the MongoDB aggregation pipeline.
 *
 * Unlike JDBC/ES, MongoDB reads are parallelized by `_id` partition, so aggregation goes through **two stages**:
 * 1. Each partition runs a `$group` (local aggregation), producing [PartialAgg] (count base for summation, sum accumulation,
 *    min/max extremes, avg's sum and non-null count);
 * 2. All partitions' [PartialAgg] are globally merged on the Beam side by [MongoAggregateCombineFn], then
 *    [MongoAggregateToRowFn] assembles the final single row (avg = sum / non-null count).
 *
 * This way aggregation is truly pushed down to MongoDB (each partition computes only inside the database) while still
 * yielding the correct global result across partitions — equivalent to Trino's "per-shard local aggregation + final merge",
 * rather than forcing a single partition as before.
 *
 * @author wuya
 */
data class PartialAgg(
    val count: Long = 0,
    /** Sum accumulated by alias (shared by sum/avg). */
    val sums: Map<String, Double> = emptyMap(),
    /** Extremes taken by alias (min/max). */
    val mins: Map<String, Double?> = emptyMap(),
    val maxs: Map<String, Double?> = emptyMap(),
    /** Non-null counts by alias (used to reconstruct avg). */
    val nonNull: Map<String, Long> = emptyMap(),
) : Serializable

/**
 * Translates the aggregation spec into the MongoDB local aggregation pipeline `[$match filter, $group {...}]`.
 * Every partition uses `_id: null` for the local `$group`; the final global merge is done by [MongoAggregateCombineFn].
 */
fun buildPartialAggregatePipeline(filter: BsonDocument, specs: List<MongoAggregateSpec>): List<Document> {
    val group = Document("_id", null)
    specs.forEachIndexed { index, spec ->
        when (spec.type) {
            "count" -> group.append(spec.alias, Document("\$sum", 1))
            "sum" -> group.append(spec.alias, Document("\$sum", "\$${spec.column}"))
            "avg" -> {
                // avg is split into sum + non-null count. The internal key is generated by position and avoids all user
                // aliases; we cannot simply concatenate `sum_<alias>`: the user could set another aggregation's as to that
                // name and the Document would silently overwrite it.
                group.append(avgInternalKey("sum", index, specs), Document("\$sum", "\$${spec.column}"))
                group.append(
                    avgInternalKey("count", index, specs),
                    Document("\$sum", Document("\$cond", listOf(Document("\$ne", listOf("\$${spec.column}", null)), 1, 0))),
                )
            }
            "min" -> group.append(spec.alias, Document("\$min", "\$${spec.column}"))
            "max" -> group.append(spec.alias, Document("\$max", "\$${spec.column}"))
        }
    }
    return listOf(Document("\$match", filter), Document("\$group", group))
}

/** Parses a single partition's `$group` result document into [PartialAgg]; an empty partition (no document) returns an all-zero [PartialAgg]. */
fun partialAggFromDoc(doc: Document?, specs: List<MongoAggregateSpec>): PartialAgg {
    if (doc == null) return PartialAgg()
    val sums = mutableMapOf<String, Double>()
    val mins = mutableMapOf<String, Double?>()
    val maxs = mutableMapOf<String, Double?>()
    val nonNull = mutableMapOf<String, Long>()
    val count = specs.firstOrNull { it.type == "count" }?.let { numericLong(doc[it.alias], it.alias) } ?: 0L
    specs.forEachIndexed { index, spec ->
        when (spec.type) {
            "count" -> {}
            "sum" -> sums[spec.alias] = numericDouble(doc[spec.alias], spec.alias) ?: 0.0
            "avg" -> {
                val sumKey = avgInternalKey("sum", index, specs)
                val countKey = avgInternalKey("count", index, specs)
                sums[spec.alias] = numericDouble(doc[sumKey], sumKey) ?: 0.0
                nonNull[spec.alias] = numericLong(doc[countKey], countKey) ?: 0L
            }
            "min" -> mins[spec.alias] = numericDouble(doc[spec.alias], spec.alias)
            "max" -> maxs[spec.alias] = numericDouble(doc[spec.alias], spec.alias)
        }
    }
    return PartialAgg(count, sums, mins, maxs, nonNull)
}

private fun avgInternalKey(kind: String, index: Int, specs: List<MongoAggregateSpec>): String {
    var key = "__hdata_avg_${kind}_$index"
    val aliases = specs.mapTo(HashSet(), MongoAggregateSpec::alias)
    while (key in aliases) key += "_"
    return key
}

private fun numericDouble(value: Any?, field: String): Double? = when (value) {
    null -> null
    is Decimal128 -> value.bigDecimalValue().toDouble()
    is Number -> value.toDouble()
    else -> throw IllegalArgumentException("MongoDB aggregation result field [$field] is not numeric: ${value.javaClass.name}")
}

private fun numericLong(value: Any?, field: String): Long? = when (value) {
    null -> null
    is Decimal128 -> value.bigDecimalValue().longValueExact()
    is Number -> value.toLong()
    else -> throw IllegalArgumentException("MongoDB aggregation result field [$field] is not an integer: ${value.javaClass.name}")
}

/**
 * Cross-partition global merge: count sums, sum accumulates, min/max take the cross-partition extremes,
 * avg's non-null count accumulates. The output is still [PartialAgg], which [MongoAggregateToRowFn] then
 * assembles into the final Row.
 */
class MongoAggregateCombineFn(
    private val specs: List<MongoAggregateSpec>,
) : Combine.CombineFn<PartialAgg, PartialAgg, PartialAgg>(), Serializable {

    override fun createAccumulator(): PartialAgg = PartialAgg()

    override fun addInput(accumulator: PartialAgg, input: PartialAgg): PartialAgg = merge(accumulator, input)

    override fun mergeAccumulators(accumulators: MutableIterable<PartialAgg>): PartialAgg =
        accumulators.fold(PartialAgg()) { a, b -> merge(a, b) }

    override fun extractOutput(accumulator: PartialAgg): PartialAgg = accumulator

    private fun merge(a: PartialAgg, b: PartialAgg): PartialAgg {
        val sums = (a.sums.keys + b.sums.keys).associateWith { (a.sums[it] ?: 0.0) + (b.sums[it] ?: 0.0) }
        val mins = (a.mins.keys + b.mins.keys).associateWith { pick(a.mins[it], b.mins[it], ::minOfSafe) }
        val maxs = (a.maxs.keys + b.maxs.keys).associateWith { pick(a.maxs[it], b.maxs[it], ::maxOfSafe) }
        val nonNull = (a.nonNull.keys + b.nonNull.keys).associateWith { (a.nonNull[it] ?: 0) + (b.nonNull[it] ?: 0) }
        return PartialAgg(a.count + b.count, sums, mins, maxs, nonNull)
    }

    private fun pick(a: Double?, b: Double?, f: (Double, Double) -> Double): Double? = when {
        a == null -> b
        b == null -> a
        else -> f(a, b)
    }

    private fun minOfSafe(a: Double, b: Double): Double = if (a <= b) a else b
    private fun maxOfSafe(a: Double, b: Double): Double = if (a >= b) a else b
}

/**
 * Assembles the merged [PartialAgg] into the final single Row. avg is reconstructed with `sums/nonNull`
 * (null if there are no non-null values).
 */
class MongoAggregateToRowFn(
    private val specs: List<MongoAggregateSpec>,
    private val outputSchema: Schema,
) : DoFn<PartialAgg, Row>() {

    @ProcessElement
    fun processElement(@Element element: PartialAgg, receiver: OutputReceiver<Row>) {
        val builder = Row.withSchema(outputSchema)
        specs.forEach { spec ->
            when (spec.type) {
                "count" -> builder.addValue(element.count)
                "sum" -> builder.addValue(element.sums[spec.alias])
                "avg" -> {
                    val c = element.nonNull[spec.alias] ?: 0L
                    builder.addValue(if (c == 0L) null else (element.sums[spec.alias] ?: 0.0) / c)
                }
                "min" -> builder.addValue(element.mins[spec.alias])
                "max" -> builder.addValue(element.maxs[spec.alias])
            }
        }
        receiver.output(builder.build())
    }

    companion object {
        private const val serialVersionUID: Long = 1
    }
}
