#!/usr/bin/env sh
# Package one descriptor JAR plus its private dependencies into a reproducible plugin directory.
set -eu

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <input-jar-directory> <output-plugin-directory>" >&2
  exit 64
fi

input_dir=$1
output_dir=$2
[ -d "$input_dir" ] || { echo "Input directory does not exist: $input_dir" >&2; exit 66; }

set -- "$input_dir"/*.jar
[ -f "$1" ] || { echo "Input directory contains no JAR files: $input_dir" >&2; exit 65; }

descriptor_count=0
descriptor_jar=
for jar in "$@"; do
  if jar tf "$jar" | grep -qx 'META-INF/hdata-plugin.properties'; then
    descriptor_count=$((descriptor_count + 1))
    descriptor_jar=$jar
  fi
done
[ "$descriptor_count" -eq 1 ] || {
  echo "Expected exactly one descriptor JAR, found $descriptor_count" >&2
  exit 65
}

id=$(unzip -p "$descriptor_jar" META-INF/hdata-plugin.properties | sed -n 's/^id=//p' | head -n 1)
api_version=$(unzip -p "$descriptor_jar" META-INF/hdata-plugin.properties | sed -n 's/^api_version=//p' | head -n 1)
provider_class=$(unzip -p "$descriptor_jar" META-INF/hdata-plugin.properties | sed -n 's/^provider_class=//p' | head -n 1)
[ -n "$id" ] && [ -n "$api_version" ] && [ -n "$provider_class" ] || {
  echo "Descriptor must define id, api_version, and provider_class" >&2
  exit 65
}

rm -rf "$output_dir"
mkdir -p "$output_dir"
cp "$@" "$output_dir/"
(
  cd "$output_dir"
  find . -maxdepth 1 -type f -name '*.jar' -printf '%f\n' | LC_ALL=C sort | while IFS= read -r jar; do
    sha256sum "$jar"
  done > hdata-plugin.sha256
)
cat > "$output_dir/hdata-plugin.lock" <<LOCK
# Generated by tools/package-plugin.sh; commit this file with plugin deployment configuration.
id=$id
api_version=$api_version
provider_class=$provider_class
descriptor_jar=$(basename "$descriptor_jar")
checksums=hdata-plugin.sha256
LOCK
printf 'Packaged plugin [%s] in %s\n' "$id" "$output_dir"
